### PR TITLE
log4j dependency cleanup

### PR DESCRIPTION
**Pull request by Emkas**
Hello,

I made 2 changes with some corrections for log4j dependency in the project:
* _client-core: don't override log4j version_ - you/we want to use one version of this dependency in all subproject. In log4j is used in several places, but only in _client-core_ the version is overwritten (on the same version)
* _Unnecessary exclusions of log4j_ - some time ago log4j dependency was updated, but exlusions were left the same. Current version of log4j doesn't need those exclusions.

(This is kind of a test for some other changes I'd like to do in the project. I'd like to get to know 'project flow' here :-))

### CODE REVIEW

**Comment by Emkas** [comment]
I'd be very grateful for any feedback. Like I said, I've made other changes (i.e. removed joda-time dependency from saml) and I'd be happy to do some more (like logging exceptions from java's ssl module in saml), but I don't know if there is any point of doing so.

**Comment by mmoayyed** [comment]
LGTM. Thanks!

**Comment by Emkas** [comment]
Hello @mmoayyed thank you for taking an interest in my PR.

And... since I have an attention of human being, would you be so kind, and spare a minute for taking look on [Spring Security: Remove CAS module #10441](https://github.com/spring-projects/spring-security/issues/10441)?

**Comment by mmoayyed** [comment]
Hello. I don't follow. What should I be looking at, exactly??

**Comment by Emkas** [comment]
Well, the first statement of Spring Security's issue. Are there any plans to support Jakarta EE 9 in `java-cas-client`?

(I think this would be "big operation", not for one person to decide.

And to be perfectly clear, I'm just an end user of both libraries, `spring-security` and `java-cas-client` - and CAS in general, but it doesn't matter here. And I'm trying to figure out how my situation would look like in the future.)

**Comment by mmoayyed** [comment]
As you surely know, this is an open-source project. There are no "plans" to do anything. Plans are made when someone shows up with a pull request, or someone pays someone to work on a pull request. Since those are unknown, I cant tell you about a pre-defined plan. All I can tell you is, atm, there are no plans since there is no pending PR, and AFAIK, nobody is paid to work on that feature. (Even pending PRs would be reviewed as time allows)

Support for Jakarta generally would happen around the time of Spring Boot 3 and Spring 6. Too soon to "plan" for anything.

**Comment by leleuj** [comment]
I'm not sure this would be such a "big operation": for now, isn't it just a package move (javax.* -> jakarta.*)?

I haven't received any request for that in https://github.com/pac4j/pac4j, but I may do it in the future for pac4j and thus, I would do it for the Java CAS client first.

**Comment by Emkas** [comment]
@mmoayyed thank you very much for the response.

@leleuj this isn't big in terms of programmistic work, but it is big in case of maintaining whole CAS and applications (it may break many of them and you must change many dependencies at once)

**Pull request merged**
