### PR TITLE
CASC-216 support session fixation by implement HttpSessionIdListener …

### PR DESCRIPTION
**Pull request by sammyhk**
…in SingleSignOutHttpSessionListener

### CODE REVIEW

**Comment by Emkas** [comment]
I didn't expect a stale bot here.

**Comment by Emkas** [comment]
@mmoayyed Why this is closed without any comment?

**Comment by mmoayyed** [comment]
Comment is, this was opened 2 years ago and there has been no activity or interest since then. We'll close and can revisit later.

**Comment by Emkas** [comment]
What other interest do you need? The change is done. Without ANY interest from Apareo. No comment, no asking for rebase etc. Do you want authors to ask about any attention once in the week? Once in a month? Once in the quarter? Please give us some guidance.

Like stale bot and some other "no unit tests" bot is not enough.

How can you expect any interest since you gave none. I've watched several PR in this project and all of them have no feedback. And now. All of them are closed. Looks like only PR this project can handle are one from the dependency bot.

**Comment by sammyhk** [comment]
I'm the author of original PR, I contributed the issue of https://apereo.atlassian.net/browse/CASC-216 2 years before, and no one reviewed or merged. Now some random guys just popup and closed the PR. Maybe this project is dead?

**Comment by sammyhk** [comment]
Interestingly, I just checked the original issue https://apereo.atlassian.net/browse/CASC-216 which created in December 27, 2013, almost 10 years before without someone to fix. Maybe that is what they called "no interest".

**Pull request closed without merging**
