### PR TITLE
CASC-231 HttpsURLConnectonFactory is Not Serializable

### PR DESCRIPTION
**Pull request by battags**
Problem: THe HttpsURLConnectionFactory is not serializable, causing problems for clients that must serialize
the principal (which depends on a ProxyRetriever).

Solution: Make the HttpsURLConnectionFactory serializable.

QA Notes: added unit test to confirm serialize-deserialize

### CODE REVIEW

**Comment by rwinch** [comment]
Please forgive the perhaps obvious question, "Any idea when this will be available in a release?"

**Comment by battags** [comment]
We should probably cut a 3.4 release soon its been quite a while :-(  We don't have everything in that we wanted though but I think we'll have to hold that off for another version.

**Comment by leleuj** [comment]
@battags : if you are about to cut a release, please consider this one: https://github.com/Jasig/java-cas-client/pull/93

**Comment by battags** [comment]
Yes -- I was hoping to avoid that one (not because there's anything wrong with what you did) but I haven't had time to put in the effort to refactor for a better approach.

**Comment by rwinch** [comment]
Thanks @battags I am looking forward to updating to the new version :)

**Comment by battags** [comment]
I think we'll want to pull in Marvin's update for the SAML dependencies before we cut a 3.4.  I think we can defer most other "3.4" items since its been a while since we cut a release :-(

**Comment by rwinch** [comment]
@battags I don't suppose there is an update on releasing cas-client-3.4?

**Comment by battags** [comment]
The goal is by the end of this week.

**Pull request merged**
