### PR TITLE
Prioritize X-Forwarded-Host when choosing the service parameter

### PR DESCRIPTION
**Pull request by inghamn**
Use X-Forwarded-Host whenever it's available.

### CODE REVIEW

**Comment by hdeadman** [comment]
That old (current) code is doing a String comparison with the == operator. Would that ever be true? Seems like dead code...

**Comment by hdeadman** [comment]
@mmoayyed Any objection to me merging this? It bothers me that we are comparing a string with == which basically makes the code dead and the X-Forwarded-Host header is always ignored. One could argue that the X-Forwarded-Host header should not be trusted (by default) since it could originate in browser if no intervening  proxy was setting it but I think the risk is low as this code is only hit if someone configures there application with multiple server names and the header value is only going to help choose between valid configured application access paths. If you don't think we should support looking at X-Forwarded-Host header then I could submit pull request to remove the code.

**Comment by mmoayyed** [comment]
I think this is fine, but I'd also like @serac to review this. Let's keep this open for a few more days to allow Marvin and others to review.

**Comment by mmoayyed** [comment]
@hdeadman Please merge as time allows.

**Comment by serac** [comment]
I apologize for not reviewing in a timely manner, but I did want to add my support for this patch. The code it replaces is pretty obviously incorrect by using `==` for string comparison.

**Comment by mmoayyed** [comment]
Thank you Marvin. Much appreciated!

**Pull request merged**
