### PR TITLE
Upgrade to Java 6

### PR DESCRIPTION
**Pull request by leleuj**

### CODE REVIEW

**Comment by battags** [comment]
+1 though we should bump our SNAPSHOT version to 3.5 if we're introducing a new minimum Java version.

**Comment by leleuj** [comment]
You're right, it might be a breaking change. I updated the version accordingly. Feel free to merge it when you want to start working on 3.5.0.

**Comment by mmoayyed** [comment]
:+1

**Comment by mmoayyed** [comment]
@leleuj could you please merge/rebase once more? I think this is good to go, right?

**Comment by leleuj** [comment]
Done

**Comment by mmoayyed** [comment]
Great. Thanks. Shall we proceed to merge?

**Comment by leleuj** [comment]
Yep. It's nothing more than a change of the version to 3.5.0-SNAPSHOT as Java 6 is a major update.

**Pull request merged**
