### PR TITLE
Handle front-channel SLO

### LINKED ISSUE #186: Rework the front-channel logout functionality
The present front-channel logout functionality requires a bit of dancing around between the client app and the CAS server, where the sequence appears to be the following:
1. Receive a logout request as a GET
2. Kill session
3. Redirect back to CAS with a special URL allowing the server to proceed to the next entry. 

This is not practical. Instead, the server should issue async logout requests via JS to apps and track the completion status of the call. These requests are somewhat identical to the back-channel logout process, (method and payload) which should help simplify the conditional logic we have today (`isFrontChannel()` & `isBackChannel()` vs `IsLogoutRequest()`) .

### PR DESCRIPTION
**Pull request by mmoayyed**
Closes #186

### CODE REVIEW

**Comment by mmoayyed** [comment]
Any objections to merging this PR by this Friday? Has anyone had a chance to review?

**Comment by mmoayyed** [comment]
Heads up; Planning to merge by Friday unless there are comments/objections. Please review if you do get a chance.

**Comment by leleuj** [comment]
Is this change really backward compatible if I'm using the experimental front-channel logout from CAS v5?

**Comment by mmoayyed** [comment]
Nothing is experimental, specially if it ships. Have you found something that might prove otherwise?

**Comment by leleuj** [comment]
In CAS 4.x, for front-channel logout, we build a logout URL with the `service` and the `RelatyState` parameters, expecting a redirection (on the client side) to the CAS server with the `RelayState` parameter. This is not handled anymore.

**Comment by mmoayyed** [comment]
Correct, none of that is relevant simply because 5 attempts to handle front-channel SLO more comprehensively.  The client is no longer required to dance around.

**Comment by leleuj** [comment]
OK. Perfect.

**Comment by mmoayyed** [comment]
Just some additional background: in 5 the goal is for the client to make async calls to all endpoints that are marked as front-channel SLO as GET I believe. So the client simply should be able to take advantage of the same SLO filter, but handle it differently. This new change will not impact existing SLO behavior with back-channel logouts of course, and in that sense it's entirely BC. Those who ran 4, and dealt with RelayState and all that would obviously be advised to upgrade to 5 to gain better functionality, or stick with 4 and upgrade to the new CAS client version continuing to the same thing they used to. 

Safe on all fronts.

**Pull request merged**
